apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  secretObjects:
    - data:
        - key: datadog-api-key
          objectName: default_datadog_api_key
        - key: datadog-app-key
          objectName: default_datadog_app_key
        - key: cluster-agent-auth-token
          objectName: default_cluster_agent_auth_token
      secretName: default-datadog
      type: Opaque
  parameters:
    objects: |
      - objectName: "default_datadog_api_key"
        objectType: "ssmparameter"
        objectVersion: "1"
      - objectName: "default_datadog_app_key"
        objectType: "ssmparameter"
        objectVersion: "1"
      - objectName: "default_cluster_agent_auth_token"
        objectType: "ssmparameter"
        objectVersion: "1"

