---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: datadog
  namespace: default
  labels: {}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxxxxxxx:role/YOUR_ROLE_NAME #IRSA
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: "datadog"
    chart: "datadog-2.19.8"
    release: "datadog"
  name: datadog-cluster-agent
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxxxxxxx:role/YOUR_ROLE_NAME #IRSA